/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/fromsukong.ts
 * Command: astryx theme build src/themes/fromsukong.ts
 * CLI: @astryxdesign/cli@0.3.0
 * Core: @astryxdesign/core@0.3.0
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const fromsukongTheme: DefinedTheme;
